## House Price Feature Engineering Case Study

## Problem Statement
The dataset contains raw property information such as price, bedrooms, bathrooms, square footage, and location. 
However, these raw features alone may not provide enough information for deeper analysis.

The objective is to create meaningful features that better represent house value, property size, and location
characteristics.

Objectives
Understand the house price dataset.
Create new features from existing variables.
Apply ratio-based feature engineering.
Create categorical and binary features.
Transform numerical variables.
Generate a feature-rich dataset for future analysis and machine learning.

In [4]:
# import
import pandas as pd

In [5]:
# load
df = pd.read_csv('house_price.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4801 entries, 0 to 4800
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BROKERTITLE                  4801 non-null   object
 1   TYPE                         4801 non-null   object
 2   PRICE                        4801 non-null   int64
 3   BEDS                         4801 non-null   int64
 4   BATH                         4801 non-null   float64
 5   PROPERTYSQFT                 4801 non-null   float64
 6   ADDRESS                      4801 non-null   object
 7   STATE                        4801 non-null   object
 8   MAIN_ADDRESS                 4801 non-null   object
 9   ADMINISTRATIVE_AREA_LEVEL_2  4801 non-null   object
 10  LOCALITY                     4801 non-null   object
 11  SUBLOCALITY                  4801 non-null   object
 12  STREET_NAME                  4801 non-null   object
 13  LONG_NAME                    4801 non-null   object
 14  FORMATTED_ADDRESS            4801 non-null   object
 15  LATITUDE                     4801 non-null   float64
 16  LONGITUDE                    4801 non-null   float64
dtypes: float64(4), int64(2), object(11)
memory usage: 637.8+ KB

In [7]:
df.head()

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.0,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.0,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.0,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.0,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.0,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856

In [8]:
df.shape

(4801, 17)

#### Dataset Summary
Records: 4801
Features: 17

In [9]:
df.isnull().sum()

BROKERTITLE                    0
TYPE                           0
PRICE                          0
BEDS                           0
BATH                           0
PROPERTYSQFT                   0
ADDRESS                        0
STATE                          0
MAIN_ADDRESS                   0
ADMINISTRATIVE_AREA_LEVEL_2    0
LOCALITY                       0
SUBLOCALITY                    0
STREET_NAME                    0
LONG_NAME                      0
FORMATTED_ADDRESS              0
LATITUDE                       0
LONGITUDE                      0
dtype: int64

In [10]:
df.duplicated().sum()

214

#### Observation
No significant missing values.
Dataset is suitable for feature engineering.

## Feature engineering
Why Feature Engineering?

Raw features provide basic information.

For example:

Existing Feature - Limitation
PRICE  - Does not consider property size
BEDS - Does not indicate room efficiency
PROPERTYSQFT- Difficult to compare directly
LOCALITY - Text information only

To address these limitations, new features will be created.

In [11]:
# Feature Creation
### Price Per Square Foot
df['PRICE_PER_SQFT'] = df['PRICE'] / df['PROPERTYSQFT']

In [12]:
df[['PRICE','PROPERTYSQFT','PRICE_PER_SQFT']].head()

       PRICE  PROPERTYSQFT  PRICE_PER_SQFT
0     315000        1400.0      225.000000
1  195000000       17545.0    11114.277572
2     260000        2015.0      129.032258
3      69000         445.0      155.056180
4   55000000       14175.0     3880.070547

#### Two properties may have the same price but very different sizes. Price per square foot provides a more accurate measure of property value than total price alone

In [13]:
# Total Rooms
df['TOTAL_ROOMS'] = df['BEDS'] + df['BATH']

In [14]:
df[['BEDS','BATH',
'TOTAL_ROOMS']].head()

   BEDS       BATH  TOTAL_ROOMS
0     2   2.000000     4.000000
1     7  10.000000    17.000000
2     4   2.000000     6.000000
3     3   1.000000     4.000000
4     7   2.373861     9.373861

#### This feature provides a combined measure of room availability within a property.

In [16]:
# Luxury Property Indicator
df['LUXURY_PROPERTY'] = (
df['PRICE'] > df['PRICE'].median()
).astype(int)

In [17]:
df['LUXURY_PROPERTY'].value_counts()

0    2407
1    2394
Name: LUXURY_PROPERTY, dtype: int64

### Creates a binary feature that distinguishes premium properties from standard properties.

In [18]:
# Property Size Category
df['SIZE_CATEGORY'] = pd.cut(
df['PROPERTYSQFT'],
bins=[0,1000,2000,3000,10000],
labels=['Small','Medium','Large','Luxury']
)

In [19]:
df['SIZE_CATEGORY'].value_counts()

Large     2128
Medium    1202
Small      891
Luxury     538
Name: SIZE_CATEGORY, dtype: int64

#### Properties are segmented into meaningful size groups for easier analysis

In [20]:
# Bedroom Density
df['BEDROOM_DENSITY'] = (
df['BEDS'] / df['PROPERTYSQFT']
)

In [21]:
df[['BEDS',
'PROPERTYSQFT',
'BEDROOM_DENSITY']].head()

   BEDS  PROPERTYSQFT  BEDROOM_DENSITY
0     2        1400.0         0.001429
1     7       17545.0         0.000399
2     4        2015.0         0.001985
3     3         445.0         0.006742
4     7       14175.0         0.000494

### Measures how efficiently available space is used

In [22]:
# Bathroom Density
df['BATHROOM_DENSITY'] = (
df['BATH'] / df['PROPERTYSQFT']
)

In [23]:
df[['BATH',
'PROPERTYSQFT',
'BATHROOM_DENSITY']].head()

        BATH  PROPERTYSQFT  BATHROOM_DENSITY
0   2.000000        1400.0          0.001429
1  10.000000       17545.0          0.000570
2   2.000000        2015.0          0.000993
3   1.000000         445.0          0.002247
4   2.373861       14175.0          0.000167

### This feature measures bathroom availability relative to property size.

In [24]:
# Log Price Transformation
import numpy as np

df['LOG_PRICE'] = np.log1p(df['PRICE'])

In [25]:
df[['PRICE',
'LOG_PRICE']].head()

       PRICE  LOG_PRICE
0     315000  12.660331
1  195000000  19.088510
2     260000  12.468441
3      69000  11.141876
4   55000000  17.822844

#### Log transformation reduces price skewness and stabilizes variance

In [26]:
# Locality Frequency Encoding
locality_freq = df['LOCALITY'].value_counts()

df['LOCALITY_FREQ'] = (
df['LOCALITY'].map(locality_freq)
)

In [27]:
df[['LOCALITY',
'LOCALITY_FREQ']].head()

   LOCALITY  LOCALITY_FREQ
0  New York           2505
1  New York           2505
2  New York           2505
3  New York           2505
4  New York           2505

#### This feature represents locality popularity based on listing frequency

In [28]:
# Broker Property Count
broker_freq = (
df['BROKERTITLE'].value_counts()
)

df['BROKER_PROPERTY_COUNT'] = (
df['BROKERTITLE'].map(broker_freq)
)

In [29]:
df[['BROKERTITLE',
'BROKER_PROPERTY_COUNT']].head()

                                         BROKERTITLE  BROKER_PROPERTY_COUNT
0        Brokered by Douglas Elliman  -111 Fifth Ave                     40
1                                Brokered by Serhant                     54
2                             Brokered by Sowae Corp                     40
3                                Brokered by COMPASS                    456
4  Brokered by Sotheby's International Realty - E...                     62

#### This feature measures broker activity based on the number of listed properties

In [19]:
df.head()

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,...,LONGITUDE,PRICE_PER_SQFT,TOTAL_ROOMS,LUXURY_PROPERTY,SIZE_CATEGORY,BEDROOM_DENSITY,BATHROOM_DENSITY,LOG_PRICE,LOCALITY_FREQ,BROKER_PROPERTY_COUNT
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.0,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,...,-73.974483,225.000000,4.000000,0,Medium,0.001429,0.001429,12.660331,2505,40
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.0,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,...,-73.980991,11114.277572,17.000000,1,NaN,0.000399,0.000570,19.088510,2505,54
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.0,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,...,-74.196109,129.032258,6.000000,0,Large,0.001985,0.000993,12.468441,2505,40
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.0,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,...,-73.974613,155.056180,4.000000,0,Small,0.006742,0.002247,11.141876,2505,456
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.0,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,...,-73.969856,3880.070547,9.373861,1,NaN,0.000494,0.000167,17.822844,2505,62

In [20]:
df.shape

(4801, 26)

### Observation

The dataset now contains additional features that better describe property value, property size, location popularity, and broker activity

### Key Insights
- Property price alone does not fully represent a house's value; Price Per Square Foot provides a more meaningful   comparison.
- Combining bedrooms and bathrooms into Total Rooms gives a better view of property size and capacity.
- Categorizing properties by size helps simplify property segmentation and comparison.
- Frequency encoding transformed location information into numerical values while preserving locality popularity.
- Engineered features provide richer information than the original dataset and can support better analysis and machine learning models.

### Conclusion

Through feature engineering, raw property data was transformed into a feature-rich dataset. The newly created features provide better insights into house value, size, and location, making the dataset more useful for future analysis and machine learning applications