# Case Study: From Data to Diagnosis handling Patient Records with Pandas
### A hospital wants to improve patient care and operational efficiency.
### They need to analyze patient encounter data to:
###  Identify trends in readmissions and costs
###  Filter and segment patients by encounter type and payer
###  Handle missing or incomplete records
###  Aggregate costs and stay durations by patient groups
### Sort and merge information for actionable insights

In [1]:
import pandas as pd
df = pd.read_csv('encounters.csv')
print("First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185347001,Encounter for problem (procedure),85.55,1018.02,0.00,NaN,NaN
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,outpatient,308335008,Patient encounter procedure,142.58,2619.36,0.00,NaN,NaN
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03T14:32:11Z,2011-01-03T14:47:11Z,73babadf-5b2b-fee7-189e-6f41ff213e01,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185349003,Encounter for check up (procedure),85.55,461.59,305.27,NaN,NaN
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03T16:24:45Z,2011-01-03T16:39:45Z,3b46a0b7-0f34-9b9a-c319-ace4a1f58c0b,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,General examination of patient (procedure),136.80,1784.24,0.00,NaN,NaN
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia

In [2]:
#Column Selection & Filtering
#Select columns of interest
possible_cols = ['Id', 'PATIENT', 'ENCOUNTERCLASS', 'BASE_ENCOUNTER_COST', 'PAYER', 'REASONDESCRIPTION']

In [3]:
possible_cols

['Id',
 'PATIENT',
 'ENCOUNTERCLASS',
 'BASE_ENCOUNTER_COST',
 'PAYER',
 'REASONDESCRIPTION']

In [10]:
# Handling Missing Values
print("\nMissing values in each column:")
df.isnull().sum()

Missing values in each column:

Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             19541
REASONDESCRIPTION      19541
dtype: int64

In [11]:
# Fill missing cost values with the median
df['REASONCODE'].fillna(df['REASONCODE'].mean(), inplace=True)

In [12]:
df['REASONDESCRIPTION'].fillna(df['REASONDESCRIPTION'].mode()[0], inplace=True)

In [13]:
df.isnull().sum()

Id                     0
START                  0
STOP                   0
PATIENT                0
ORGANIZATION           0
PAYER                  0
ENCOUNTERCLASS         0
CODE                   0
DESCRIPTION            0
BASE_ENCOUNTER_COST    0
TOTAL_CLAIM_COST       0
PAYER_COVERAGE         0
REASONCODE             0
REASONDESCRIPTION      0
dtype: int64

In [14]:
# Average cost per encounter class
avg_cost_by_class = df.groupby('ENCOUNTERCLASS')['BASE_ENCOUNTER_COST'].mean()
print("\nAverage Base Encounter Cost by Encounter Class:")
print(avg_cost_by_class)

Average Base Encounter Cost by Encounter Class:
ENCOUNTERCLASS
ambulatory    105.729076
emergency     145.248307
inpatient     113.673771
outpatient    105.039776
urgentcare    142.580000
wellness      136.800000
Name: BASE_ENCOUNTER_COST, dtype: float64

In [15]:
#Total claim cost by payer
total_claim_by_payer = df.groupby('PAYER')['TOTAL_CLAIM_COST'].sum()
print("\nTotal Claim Cost by Payer:")
total_claim_by_payer

Total Claim Cost by Payer:

PAYER
047f6ec3-6215-35eb-9608-f9dda363a44c     2424532.96
42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a     2982715.05
4d71f845-a6a9-3c39-b242-14d25ef86a8d     2589956.10
5059a55e-5d6e-34d1-b6cb-d83d16e57bcf     2563507.98
6e2f1a2d-27bd-3701-8d08-dae202c58632     3002166.01
7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a     8954131.02
7caa7254-5050-3b5e-9eae-bd5ea30e809c    24647228.89
b1c428d6-4f07-31e0-90f0-68ffa6ff8c76    49259290.16
b3221cfc-24fb-339e-823d-bc4136cbc4ed     1546925.99
d47b3510-2895-3b70-9897-342d681c769d     3543921.36
Name: TOTAL_CLAIM_COST, dtype: float64

In [16]:
df.head()

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185347001,Encounter for problem (procedure),85.55,1018.02,0.00,4.751643e+11,Chronic congestive heart failure (disorder)
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,outpatient,308335008,Patient encounter procedure,142.58,2619.36,0.00,4.751643e+11,Chronic congestive heart failure (disorder)
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03T14:32:11Z,2011-01-03T14:47:11Z,73babadf-5b2b-fee7-189e-6f41ff213e01,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185349003,Encounter for check up (procedure),85.55,461.59,305.27,4.751643e+11,Chronic congestive heart failure (disorder)
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03T16:24:45Z,2011-01-03T16:39:45Z,3b46a0b7-0f34-9b9a-c319-ace4a1f58c0b,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,General examination of patient (procedure),136.80,1784.24,0.00,4.751643e+11,Chronic congestive heart failure (disorder)
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,5.582200e+07,Hyperlipidemia

In [17]:
# Sort encounters by highest base cost
sorted_df = df.sort_values(by='BASE_ENCOUNTER_COST', ascending=False)
print("\nTop 5 most expensive encounters:")
sorted_df[['Id', 'BASE_ENCOUNTER_COST']].head()

Top 5 most expensive encounters:

                                         Id  BASE_ENCOUNTER_COST
10578  e8000330-e916-47ee-7549-5074c10fba44               146.18
5623   94d1258d-5f24-67b2-baac-721b7755c1f9               146.18
2713   df8a68e0-e1b8-cf25-2862-d2daf019ec8f               146.18
5633   b45be886-78b4-518a-8e74-471fb0e9bdcf               146.18
2715   c8fc9632-8946-56d1-19bc-b01654e0a03e               146.18

In [18]:
df.head()

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185347001,Encounter for problem (procedure),85.55,1018.02,0.00,4.751643e+11,Chronic congestive heart failure (disorder)
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,outpatient,308335008,Patient encounter procedure,142.58,2619.36,0.00,4.751643e+11,Chronic congestive heart failure (disorder)
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03T14:32:11Z,2011-01-03T14:47:11Z,73babadf-5b2b-fee7-189e-6f41ff213e01,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185349003,Encounter for check up (procedure),85.55,461.59,305.27,4.751643e+11,Chronic congestive heart failure (disorder)
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03T16:24:45Z,2011-01-03T16:39:45Z,3b46a0b7-0f34-9b9a-c319-ace4a1f58c0b,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,General examination of patient (procedure),136.80,1784.24,0.00,4.751643e+11,Chronic congestive heart failure (disorder)
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,5.582200e+07,Hyperlipidemia